spring:
  application:
    name: fraud-service
  datasource:
    url: jdbc:clickhouse://localhost:8123/fraud-service
    username: bnpl_user
    password: bnpl_pass
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/