server:
  port: 8085

spring:
  datasource:
    url: jdbc:clickhouse://localhost:8123/frauddb?compress=0
    username: bnpl_user
    password: bnpl_pass
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver

    jpa:
      database-platform: org.hibernate.dialect.GenericDialect
      show-sql: true
      hibernate:
        ddl-auto: update


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info
fraud:
  threshold: 0.7
  velocity-window-minutes: 30
  velocity-max-tx: 5
  amount-anomaly-factor: 2.0
  weight-amount: 0.4
  weight-velocity: 0.3
  weight-ip-device: 0.1