

spring:
  application:
    name: product-service
  server:
    port: 8040
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
    elasticsearch:
      client:
        elasticsearch:
          uris: http://localhost:9200


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
