eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8180/realms/bnpl-platform"
  application:
    name: user-service
  server:
    port: 8980


  datasource:
    url: jdbc:postgresql://localhost:5432/user-service

    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:

    database-platform: org.hibernate.dialect.PostgreSQLDialect

